version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitness
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  backend:
    build: ./backend
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  client:
    build: ./client
    command: pnpm dev --host --port 4321
    env_file:
      - client/.env
    volumes:
      - ./client:/app
    ports:
      - "4321:4321"
    depends_on:
      - backend

volumes:
  pgdata:


