"""update_badge_model

Revision ID: 1fb30902280f
Revises: 14760f0c41d0
Create Date: 2025-09-14 09:34:43.728816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb30902280f'
down_revision: Union[str, Sequence[str], None] = '14760f0c41d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###

  # Create enum types first
  badge_category_enum = sa.Enum('first_steps', 'consistency', 'special_achievements',
                                'wellness', 'fitness', 'social', name='badgecategoryenum')
  badge_category_enum.create(op.get_bind())

  badge_status_enum = sa.Enum(
      'earned', 'in_progress', 'locked', name='badgestatus')
  badge_status_enum.create(op.get_bind())

  # Add columns
  op.add_column('badges', sa.Column(
      'badge_id', sa.String(length=64), nullable=False))
  op.add_column('badges', sa.Column(
      'title', sa.String(length=255), nullable=False))
  op.add_column('badges', sa.Column('description', sa.Text(), nullable=False))
  op.add_column('badges', sa.Column(
      'category', badge_category_enum, nullable=False))
  op.add_column('badges', sa.Column(
      'icon_url', sa.String(length=512), nullable=True))
  op.add_column('badges', sa.Column(
      'emoji', sa.String(length=10), nullable=True))
  op.add_column('badges', sa.Column(
      'status', badge_status_enum, nullable=False))
  op.add_column('badges', sa.Column(
      'progress_current', sa.Integer(), nullable=True))
  op.add_column('badges', sa.Column(
      'progress_target', sa.Integer(), nullable=True))
  op.add_column('badges', sa.Column(
      'earned_at', sa.DateTime(timezone=True), nullable=True))
  op.add_column('badges', sa.Column('requirements', sa.Text(), nullable=True))
  op.add_column('badges', sa.Column(
      'created_at', sa.DateTime(timezone=True), nullable=True))

  # Set default value for existing rows
  op.execute("UPDATE badges SET created_at = NOW() WHERE created_at IS NULL")
  # Make it NOT NULL after setting defaults
  op.alter_column('badges', 'created_at', nullable=False)

  op.drop_constraint(op.f('badges_code_key'), 'badges', type_='unique')
  op.drop_column('badges', 'code')
  op.drop_column('badges', 'achieved_at')
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('badges', sa.Column('achieved_at', postgresql.TIMESTAMP(
      timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
  op.add_column('badges', sa.Column('code', sa.VARCHAR(
      length=64), autoincrement=False, nullable=False))
  op.create_unique_constraint(op.f('badges_code_key'), 'badges', [
                              'code'], postgresql_nulls_not_distinct=False)
  op.drop_column('badges', 'created_at')
  op.drop_column('badges', 'requirements')
  op.drop_column('badges', 'earned_at')
  op.drop_column('badges', 'progress_target')
  op.drop_column('badges', 'progress_current')
  op.drop_column('badges', 'status')
  op.drop_column('badges', 'emoji')
  op.drop_column('badges', 'icon_url')
  op.drop_column('badges', 'category')
  op.drop_column('badges', 'description')
  op.drop_column('badges', 'title')
  op.drop_column('badges', 'badge_id')

  # Drop enum types
  sa.Enum(name='badgestatus').drop(op.get_bind())
  sa.Enum(name='badgecategoryenum').drop(op.get_bind())
  # ### end Alembic commands ###
