"""change habits table

Revision ID: 4251a0de8294
Revises: 8ad8f9d50fb5
Create Date: 2025-09-08 22:02:55.349371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4251a0de8294'
down_revision: Union[str, Sequence[str], None] = '8ad8f9d50fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'description')
    # ### end Alembic commands ###
