"""add_category_to_habits

Revision ID: 8ad8f9d50fb5
Revises: 6688d1d19022
Create Date: 2025-09-08 13:13:36.345136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad8f9d50fb5'
down_revision: Union[str, Sequence[str], None] = '6688d1d19022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # Create the enum type first
  category_enum = sa.Enum('health', 'fitness', 'productivity', 'learning',
                          'mindfulness', 'social', 'creative', 'financial', 'other', name='category')
  category_enum.create(op.get_bind())

  # Add the column with the enum type
  op.add_column('habits', sa.Column('category', category_enum,
                nullable=False, server_default='other'))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('habits', 'category')
  # Drop the enum type
  sa.Enum(name='category').drop(op.get_bind())
  # ### end Alembic commands ###
