"""update_habit_category

Revision ID: aefa03a3164b
Revises: 2c726b9b3b19
Create Date: 2025-09-14 02:17:55.542205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefa03a3164b'
down_revision: Union[str, Sequence[str], None] = '2c726b9b3b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # This migration was empty - the hobby category was added in a later migration
  # See: e28666166609_add_hobby_to_category_enum.py
  pass
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # This migration was empty - no changes to revert
  pass
  # ### end Alembic commands ###
