"""add_quantity_to_habit_logs

Revision ID: b657aee89011
Revises: 52c0dde262e4
Create Date: 2025-09-10 01:22:05.044749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b657aee89011'
down_revision: Union[str, Sequence[str], None] = '52c0dde262e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # Add column with default value first
  op.add_column('habit_logs', sa.Column(
      'quantity', sa.Integer(), nullable=True, server_default='1'))

  # Update existing records to have quantity = 1
  op.execute("UPDATE habit_logs SET quantity = 1 WHERE quantity IS NULL")

  # Now make the column NOT NULL
  op.alter_column('habit_logs', 'quantity',
                  nullable=False, server_default=None)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('habit_logs', 'quantity')
  # ### end Alembic commands ###
