name: Backend ci
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: pip install poetry==1.8.3
      - name: Install deps
        working-directory: backend
        run: poetry install --no-interaction --no-ansi
      - name: Lint
        working-directory: backend
        run: |
          poetry run ruff check .
          poetry run black --check .
      - name: Test
        working-directory: backend
        run: poetry run pytest -q --cov
