name: Backend ci
on:
  pull_request:
    branches: [ main, production ]
    types: [opened, ready_for_review]
    # types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: backend-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Install deps
        working-directory: backend
        run: uv sync
      - name: Lint
        working-directory: backend
        run: |
          uv run ruff check .
      - name: Test
        working-directory: backend
        # run: uv run pytest -q --cov
        run: uv run pytest -qq --cov
