name: Client ci
on:
  pull_request:
    branches: [ main, production ]
jobs:
  build:
    name: client-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install deps
        working-directory: client
        run: npm ci
      - name: Lint & Typecheck
        working-directory: client
        run: |
          npm run lint || true
          npm run typecheck
      - name: Build
        working-directory: client
        run: npm run build
        